blank_issues_enabled: true
contact_links:
  - name: 'Security report'
    url: 'https://github.com/JorisJonkers-dev/.github/security/advisories/new'
    about: 'Report sensitive vulnerabilities through a private advisory.'
